<?php require __DIR__ . '/header.phtml' ?>
<?php require __DIR__ . '/alert.phtml' ?>
        <div class="small reveal card" id="syncmodal" data-reveal>
            <div class="card-divider">
                Sync mails from provider
            </div>
            <div class="card-section">
                <p>This can take a while :c</p>
                <div class="button-group">
                    <button name="sync" class="button btn-sync" data-syncFromServer><span>Sync</span></button>
                    <button name="cancel" onclick="$('#syncmodal').foundation('close')" class="button secondary">Cancel</button>
                </div>
            </div>
        </div>
        <div class="small reveal" id="mailmodal" data-reveal></div>
        <div class="small reveal" id="alertModal" data-reveal></div>
        <div id="maindrag" class="board-conta container">
                <div
                class="board-column dropzone"
                v-on:dragenter="dragEnter"
                v-on:dragleave="dragLeave"
                v-on:dragover="dragOver"
                v-on:drop="dropElement"
                v-for="(column, index) in columns"
                v-bind:id="index">
                    <h3>{{ column.title }}</h3>
                    <ul v-bind:id="index">
                        <li class="draghere card" v-bind:id="index">
                            Aqui!
                        </li>
                        <li
                        class="card draggable"
                        v-on:dragstart="dragStart"
                        v-on:dragend="dragEnd"
                        v-on:click="openMail"
                        v-for="(card, index) in column.cards"
                        v-bind:id="index"
                        v-bind:key="index"
                        v-bind:draggable="true"
                        v-if="card"
                        >
                            <div class="card-title">{{ card.subject }}</div>
                            <small>{{ card.from }}</small>
                        </li>
                    </ul>
                </div>
        </div>
<?php require __DIR__ . '/footer.phtml' ?>
