<?php require __DIR__ . '/doc-header.phtml' ?>
<?php require __DIR__ . '/header.phtml' ?>
<?php require __DIR__ . '/alert.phtml' ?>
        <div id="maindrag" class="board-conta container grid-frame grid-x">
                <div
                class="board-column dropzone cell"
                v-on:dragenter="dragEnter"
                v-on:dragleave="dragLeave"
                v-on:dragover="dragOver"
                v-on:drop="dropElement"
                v-for="(column, index) in columns"
                v-bind:id="index">
                    <h3 data-clickColumnTitle>{{ column.title }}</h3>
                    <ul v-bind:id="index">
                        <li class="draghere card" v-bind:id="index">
                            Drop Here!
                        </li>
                        <li
                        class="card draggable"
                        v-on:dragstart="dragStart"
                        v-on:dragend="dragEnd"
                        v-on:click="openMail"
                        v-for="(card, index) in column.cards"
                        v-bind:id="index"
                        v-bind:key="index"
                        v-bind:draggable="true"
                        v-if="card"
                        >
                            <div class="card-title">{{ card.subject }}</div>
                            <small>{{ card.from }}</small>
                        </li>
                    </ul>
                </div>
        </div>
<?php require __DIR__ . '/footer.phtml' ?>
