<?php require __DIR__ . '/header.phtml' ?>
        <div id="#signModal" class="container grid-x" style="margin-top: 4em;">
            <div class="medium-4 medium-offset-4">
                <div class="card">
                    <div class="card-divider">
                        Log in your Gmail account!
                    </div>
                    <div class="card-section">
                        <form class="mailform" action="/newuser" method="post">
                            <input type="email" name="email" id="email" placeholder="yourmail@gmail.com">
                            <input type="password" name="password" id="password" placeholder="Your super password">
                            <button type="submit" name="button" class="button expanded">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
<?php require __DIR__ . '/footer.phtml' ?>
