<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Waddle</title>
        <link rel="stylesheet" href="css/foundation.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/motion-ui/1.1.1/motion-ui.min.css" />
        <link rel="stylesheet" href="fonts/foundation-icons.css">
        <link rel="stylesheet" href="css/btn-ajax-loader.css">
        <link rel="stylesheet" href="css/alert.css">
        <link rel="stylesheet" href="css/app.css">
        <script src="js/vue.js" charset="utf-8"></script>
    </head>
    <body>
