        </div>
        <div id="ajax-loader"><span></span></div>
        <script src="js/jquery.js" charset="utf-8"></script>
        <script src="js/what-input.js" charset="utf-8"></script>
        <script src="js/foundation.js" charset="utf-8"></script>
        <script src="js/sweetalert2.all.min.js" charset="utf-8"></script>
        <script src="js/app.js" charset="utf-8"></script>
    </body>
</html>
