<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Waddle</title>
        <link rel="stylesheet" href="css/foundation.min.css">
        <link rel="stylesheet" href="css/app.css">
        <script src="js/vue.js" charset="utf-8"></script>
    </head>
    <body>
        <header class="top-bar">
            <div class="top-bar-left">
                <ul class="menu">
                    <li class="menu-text">Waddle</li>
                    <li><a href="#" name="button" onclick="syncFromServer(event)">Sincronizar Emails</a></li>
                </ul>
            </div>
            <div class="top-bar-right"></div>
        </header>
